# Generated by Django 5.2.7 on 2025-10-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_simplify_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
