# Generated by Django 4.2.7 on 2025-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand_product_category_product_frame_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='PKR', help_text='Currency code (e.g., PKR, USD)', max_length=10),
        ),
    ]
